<br />
<div class="panel panel-default center-block" style="width: 800px;">
    <div class="panel-heading" >Login</div>
    <div class="panel-body" > 
        <form  role="form" method="POST" >
            <div class="form-group">
                <label for ="Email">Email :</label>
                <input id="Email" type="email" name="email" value="" class="form-control"/>
            </div>
            <div class="form-group">
                <label for ="Password">Password</label>
                <input id="Password" type="password" name="password" value="" class="form-control"/>
                
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer" name="Envoyer" class="btn btn-default"/>
                    <?php
                if (isset($_COOKIE['errUser'])): echo $_COOKIE['errUser'];
                endif;
                ?>
            </div>
        </form>
    </div>
</div>
