<br />
<br />

<div class="panel panel-default center-block" style="width: 680px; opacity:0.7;">
    <div class="panel-heading" style="opacity:1; ">Inscription</div>
    <div class="panel-body" style="opacity:1; " > 
        <form  role="form" method="POST" >
            <div class="form-group">
                <label for ="sujet">Nom :</label>
                <input id="nom" type="text" name="nom" value="" class="form-control"/>
                 <?php
                if (isset($_COOKIE['errUser'])): echo $_COOKIE['errUser'];
                endif;
                ?>
            </div>
            <div class="form-group">
                <label for ="sujet">Prénom :</label>
                <input id="prenom" type="text" name="prenom" value="" class="form-control"/>
                 <?php
                if (isset($_COOKIE['errPrenom'])): echo $_COOKIE['errPrenom'];
                endif;
                ?>
            </div>
            <div class="form-group">
                <label for ="sujet">adresse :</label>
                <textarea id="adresse"  name="adresse" value="" rows="14" cols="20" class="form-control"></textarea>
                 <?php
                if (isset($_COOKIE['errAdresse'])): echo $_COOKIE['errAdresse'];
                endif;
                ?>
            </div>
            <div class="form-group">
                <label for ="Password">Password (+ 6 lettres / chiffres ):</label>
                <input id="Password" type="password" name="password" value="" class="form-control"/>
                 <?php
                if (isset($_COOKIE['errPass'])): echo $_COOKIE['errPass'];
                endif;
                ?>
            </div>
            <div class="form-group">
                <label for ="Email">Email :</label>
                <input id="Email" type="email" name="email" value="" class="form-control"/>
                 <?php
                if (isset($_COOKIE['errMail'])): echo $_COOKIE['errMail'];
                endif;
                ?>
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer" name="Envoyer" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>
